# Generated by Django 3.0 on 2021-06-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
    ]
