# Generated by Django 3.0 on 2021-06-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_order_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_ordered',
        ),
    ]
