# Generated by Django 3.0 on 2021-06-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210626_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.Product'),
        ),
    ]
