# Generated by Django 3.0 on 2021-06-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210627_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
