# Generated by Django 3.0 on 2021-08-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_auto_20210721_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
