# Generated by Django 3.0 on 2021-06-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='reg_no',
            field=models.CharField(max_length=20),
        ),
    ]
