# Generated by Django 3.0 on 2021-06-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210615_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='category',
            field=models.CharField(default='Company', max_length=30),
        ),
    ]
