# Generated by Django 3.0 on 2021-08-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companyprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
