# Generated by Django 3.0 on 2021-08-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20210804_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
