# Generated by Django 3.0 on 2021-08-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20210804_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='account_number',
            field=models.CharField(default='344643', max_length=25),
        ),
    ]
