# Generated by Django 3.0 on 2021-08-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20210804_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='account_number',
            field=models.CharField(max_length=10),
        ),
    ]
