# Generated by Django 3.0 on 2021-07-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assignedTo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
