# Generated by Django 3.0 on 2021-07-04 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0002_order_assignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 4, 23, 56, 36, 12255), null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 6, 23, 56, 36, 11284), null=True),
        ),
    ]
