# Generated by Django 3.0 on 2021-07-07 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0007_auto_20210706_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, choices=[('Ilala', 'Ilala'), ('Kinondoni', 'Kinondoni'), ('Temeke', 'Temeke'), ('Ubungo', 'Ubungo'), ('Kigamboni', 'Kigamboni')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderID',
            field=models.CharField(default=['8', 'G', 'R', 'E', 'Q', '7', 'Q', 'B', 'I', 'G', 'I', 'O', '6', 'A', 'N', '9', '5', 'L', '6', 'F', '0', 'O', 'K', '7', 'C'], max_length=25),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 7, 13, 10, 20, 364355), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 13, 10, 20, 362612), null=True),
        ),
    ]
