# Generated by Django 3.0 on 2021-07-07 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0008_auto_20210707_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 7, 13, 11, 53, 266686), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 13, 11, 53, 265844), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(default='FS0DJZ0Y4D54Z1C7FXHNQ1F5J', max_length=25),
        ),
    ]
