# Generated by Django 3.0 on 2021-07-07 13:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addtocart', '0009_auto_20210707_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 7, 13, 17, 43, 333445), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 13, 17, 43, 332022), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(default='CV0YT0GAJYS81L7CRNHU6E140', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
