# Generated by Django 3.0 on 2021-07-07 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0012_auto_20210707_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 7, 13, 49, 21, 599629), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 13, 49, 21, 598792), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(default='D1XGWW6J5S6TKCGIVYM3CJ1QE', max_length=25),
        ),
    ]
