# Generated by Django 3.0 on 2021-07-07 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0014_auto_20210707_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 7, 14, 32, 34, 918926), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 14, 32, 34, 917669), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(default='SSJDPRZ42PRO3F6WKBZK756L3', max_length=25),
        ),
    ]
