# Generated by Django 3.0 on 2021-07-07 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0015_auto_20210707_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 7, 14, 36, 2, 723291), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 14, 36, 2, 722397), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(default='5PCH5166OD06BSBUFMA1K4JWG', max_length=25),
        ),
    ]
