# Generated by Django 3.0 on 2021-07-13 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0024_auto_20210713_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 14, 57, 52, 73481), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 15, 14, 57, 52, 72583), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_ordered',
            field=models.BooleanField(),
        ),
    ]
