# Generated by Django 3.0 on 2021-07-14 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0028_auto_20210714_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='receiver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sender',
            field=models.CharField(blank=True, default='admin', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 14, 14, 41, 55, 183716), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 16, 14, 41, 55, 180605), null=True),
        ),
    ]
