# Generated by Django 3.0 on 2021-07-16 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0045_auto_20210716_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 16, 17, 13, 12, 365011), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 18, 17, 13, 12, 364104), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mode',
            field=models.CharField(blank=True, choices=[('Pick at station', 'Pick at station'), ('Door step pickup', 'Door step pickup')], max_length=100, null=True),
        ),
    ]
