# Generated by Django 3.0 on 2021-07-21 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0047_auto_20210719_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 11, 29, 18, 193646), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 23, 11, 29, 18, 192818), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mode',
            field=models.CharField(blank=True, default='Pick at station', max_length=100, null=True),
        ),
    ]
