# Generated by Django 3.0 on 2021-07-21 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0048_auto_20210721_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 11, 34, 25, 70261), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 23, 11, 34, 25, 69453), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mode',
            field=models.CharField(blank=True, choices=[('Pick at station', 'Pick at station'), ('Door step pickup', 'Door step pickup')], default='Pick at station', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
