# Generated by Django 3.0 on 2021-08-01 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0054_auto_20210729_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='arrived_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 1, 12, 22, 6, 607734), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 3, 12, 22, 6, 606001), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order received', 'Order received'), ('On pending', 'On pending'), ('On processing', 'On processing'), ('Completed', 'Completed'), ('On delivery', 'On delivery'), ('Order cancelled', 'Order cancelled')], max_length=200),
        ),
    ]
