# Generated by Django 3.0 on 2021-06-09 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='')),
                ('region', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('location', models.TextField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
