# Generated by Django 3.0 on 2021-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
