# Generated by Django 3.0 on 2021-06-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryman', '0002_auto_20210613_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
