# Generated by Django 3.0 on 2021-06-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryman', '0003_auto_20210614_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryprofile',
            name='category',
            field=models.CharField(default='Laundryman', max_length=30),
        ),
    ]
