# Generated by Django 3.0 on 2021-08-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryman', '0005_auto_20210804_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryprofile',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
