# Generated by Django 3.0 on 2021-08-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryman', '0006_auto_20210804_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryprofile',
            name='account_number',
            field=models.CharField(default='123344', max_length=25),
        ),
    ]
