# Generated by Django 3.0 on 2021-08-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryman', '0007_laundryprofile_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryprofile',
            name='account_number',
            field=models.CharField(max_length=25),
        ),
    ]
