# Generated by Django 3.0 on 2021-08-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundryman', '0008_auto_20210804_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundryprofile',
            old_name='tele',
            new_name='tele',
        ),
    ]
