# Generated by Django 3.0 on 2021-08-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryman', '0009_auto_20210812_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryprofile',
            name='account_number',
            field=models.CharField(max_length=10),
        ),
    ]
