# Generated by Django 3.0 on 2021-06-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
