# Generated by Django 3.0 on 2021-06-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20210616_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile0',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
